In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
import glob
import os

In [ ]:
benignData= pd.read_csv("/content/drive/MyDrive/ISM/benign_traffic.csv")

In [ ]:
benignData.columns

Index(['MI_dir_L5_weight', 'MI_dir_L5_mean', 'MI_dir_L5_variance',
       'MI_dir_L3_weight', 'MI_dir_L3_mean', 'MI_dir_L3_variance',
       'MI_dir_L1_weight', 'MI_dir_L1_mean', 'MI_dir_L1_variance',
       'MI_dir_L0.1_weight',
       ...
       'HpHp_L0.1_radius', 'HpHp_L0.1_covariance', 'HpHp_L0.1_pcc',
       'HpHp_L0.01_weight', 'HpHp_L0.01_mean', 'HpHp_L0.01_std',
       'HpHp_L0.01_magnitude', 'HpHp_L0.01_radius', 'HpHp_L0.01_covariance',
       'HpHp_L0.01_pcc'],
      dtype='object', length=115)

In [ ]:
benignData.head()

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_radius,HpHp_L0.1_covariance,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc
0,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,...,0.000000,0.0,0.0,1.000000,60.000000,0.000000,60.000000,0.000000,0.0,0.0
1,1.000000,354.000000,0.000000,1.000000,354.000000,0.000000,1.000000,354.000000,0.000000,1.000000,...,34.095047,0.0,0.0,5.319895,344.262695,4.710446,344.262695,22.188299,0.0,0.0
2,1.857879,360.458980,35.789338,1.912127,360.275733,35.923972,1.969807,360.091968,35.991542,1.996939,...,100.081513,0.0,0.0,6.318264,347.703087,9.034660,347.703087,81.625077,0.0,0.0
3,1.000000,337.000000,0.000000,1.000000,337.000000,0.000000,1.000000,337.000000,0.000000,1.000000,...,0.000000,0.0,0.0,1.000000,337.000000,0.000000,337.000000,0.000000,0.0,0.0
4,1.680223,172.140917,18487.448750,1.793580,182.560279,18928.175300,1.925828,193.165753,19153.795810,1.992323,...,0.000000,0.0,0.0,1.000000,60.000000,0.000000,60.000000,0.000000,0.0,0.0

In [ ]:
gafgytData=pd.concat(map(pd.read_csv, glob.glob(os.path.join("/content/drive/MyDrive/ISM/gafgyt", "*.csv"))), ignore_index= True)

In [ ]:
gafgytData.head()

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_radius,HpHp_L0.1_covariance,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc
0,1.000000,98.000000,0.000000e+00,1.000000,98.000000,0.000000,1.000000,98.000000,0.000000e+00,1.000000,...,0.000000e+00,0.0,0.0,1.000000,98.0,0.000000,98.000000,0.000000e+00,0.0,0.0
1,1.029000,98.000000,1.818989e-12,1.119520,98.000000,0.000000,1.492583,98.000000,3.637979e-12,1.931640,...,1.818989e-12,0.0,0.0,1.992944,98.0,0.000001,138.592929,1.818989e-12,0.0,0.0
2,1.504156,76.725612,2.281808e+02,1.729662,79.499272,249.746357,2.294102,84.051188,2.517926e+02,2.904273,...,0.000000e+00,0.0,0.0,1.000000,66.0,0.000000,114.856432,0.000000e+00,0.0,0.0
3,2.460087,75.617679,1.372200e+02,2.699075,77.461807,164.269331,3.280499,80.987267,1.964467e+02,3.902546,...,0.000000e+00,0.0,0.0,1.000000,74.0,0.000000,74.000000,0.000000e+00,0.0,0.0
4,3.460055,75.150149,9.809937e+01,3.699054,76.525944,122.224798,4.280490,79.354915,1.592943e+02,4.902545,...,0.000000e+00,0.0,0.0,1.000000,74.0,0.000000,74.000000,0.000000e+00,0.0,0.0

In [ ]:
miraiData=pd.concat(map(pd.read_csv,glob.glob(os.path.join("/content/drive/MyDrive/ISM/mirai", "*.csv"))), ignore_index= True)

In [ ]:
miraiData.head()

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_radius,HpHp_L0.1_covariance,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc
0,1.000000,566.0,0.000000e+00,1.000000,566.0,0.000000e+00,1.000000,566.0,0.000000e+00,1.000000,...,0.0,0.0,0.0,1.0,566.0,0.0,566.0,0.0,0.0,0.0
1,1.996585,566.0,5.820766e-11,1.997950,566.0,5.820766e-11,1.999316,566.0,0.000000e+00,1.999932,...,0.0,0.0,0.0,1.0,566.0,0.0,566.0,0.0,0.0,0.0
2,2.958989,566.0,0.000000e+00,2.975291,566.0,5.820766e-11,2.991729,566.0,5.820766e-11,2.999171,...,0.0,0.0,0.0,1.0,566.0,0.0,566.0,0.0,0.0,0.0
3,3.958979,566.0,0.000000e+00,3.975285,566.0,0.000000e+00,3.991727,566.0,1.164153e-10,3.999171,...,0.0,0.0,0.0,1.0,566.0,0.0,566.0,0.0,0.0,0.0
4,4.914189,566.0,1.164153e-10,4.948239,566.0,5.820766e-11,4.982654,566.0,5.820766e-11,4.998261,...,0.0,0.0,0.0,1.0,566.0,0.0,566.0,0.0,0.0,0.0

In [ ]:
benignData=benignData.dropna()
gafgytData=gafgytData.dropna()
miraiData=miraiData.dropna()

In [ ]:
benignData['Type']=1
gafgytData['Type']=-1
miraiData['Type']=-1

In [ ]:
from sklearn.model_selection import train_test_split
trainSet, testSet = train_test_split(benignData,test_size=0.2, random_state=0,shuffle=True)

In [ ]:
testSet=testSet.append(gafgytData,ignore_index = True)
testSet=testSet.append(miraiData,ignore_index = True)
testSet=testSet.sample(frac=1)

In [ ]:
trainX=trainSet.loc[:,~trainSet.columns.isin(['Type'])]
trainY=trainSet.loc[:,trainSet.columns.isin(['Type'])]
testX=testSet.loc[:,~testSet.columns.isin(['Type'])]
testY=testSet.loc[:,testSet.columns.isin(['Type'])]
testY

        Type
14326     -1
514590    -1
519918    -1
810837    -1
861231    -1
...      ...
540529    -1
703527    -1
411465    -1
289931    -1
171838    -1

[978660 rows x 1 columns]

In [ ]:
from sklearn.svm import OneClassSVM
svm = OneClassSVM(kernel='rbf',nu=0.2,gamma=0.1)
svm.fit(trainX)

OneClassSVM(gamma=0.1, nu=0.2)

In [ ]:
prediction=svm.predict(testX[:50000])
prediction

array([-1, -1, -1, ..., -1, -1, -1])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

matrix = confusion_matrix(testY[:50000],prediction, labels=[1,-1])
matrix

array([[  101,   404],
       [    0, 49495]])

array([[  101,   404],
       [    0, 49495]])

In [ ]:
matrix = classification_report(testY[:50000],prediction,labels=[1,-1])
matrix
accuracy_score(testY[:50000],prediction)

0.99192

0.99192

#Autoencoder

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import Model, Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from tensorflow.keras.losses import MeanSquaredLogarithmicError

In [ ]:
min_max_scaler = MinMaxScaler(feature_range=(0, 1))
x_train_scaled = min_max_scaler.fit_transform(trainX.copy())
x_test_scaled = min_max_scaler.transform(testX.copy())

In [ ]:
class AutoEncoder(Model):
  """
  Parameters
  ----------
  output_units: int
    Number of output units
  
  code_size: int
    Number of units in bottle neck
  """

  def __init__(self, output_units, code_size=8):
    super().__init__()
    self.encoder = Sequential([
      Dense(64, activation='relu'),
      Dropout(0.1),
      Dense(32, activation='relu'),
      Dropout(0.1),
      Dense(16, activation='relu'),
      Dropout(0.1),
      Dense(code_size, activation='relu')
    ])
    self.decoder = Sequential([
      Dense(16, activation='relu'),
      Dropout(0.1),
      Dense(32, activation='relu'),
      Dropout(0.1),
      Dense(64, activation='relu'),
      Dropout(0.1),
      Dense(output_units, activation='sigmoid')
    ])
  
  def call(self, inputs):
    encoded = self.encoder(inputs)
    decoded = self.decoder(encoded)
    return decoded

In [ ]:
model = AutoEncoder(output_units=x_train_scaled.shape[1])
# configurations of model
model.compile(loss='msle', metrics=['mse'], optimizer='adam')

history = model.fit(
    x_train_scaled,
    x_train_scaled,
    epochs=20,
    batch_size=512,
    validation_data=(x_test_scaled, x_test_scaled)
)

Epoch 1/20
78/78 [==============================] - 12s 95ms/step - loss: 0.0417 - mse: 0.0640 - val_loss: 2.7262 - val_mse: 44900.1758
Epoch 2/20
78/78 [==============================] - 5s 63ms/step - loss: 0.0050 - mse: 0.0076 - val_loss: 2.7265 - val_mse: 44900.1797
Epoch 3/20
78/78 [==============================] - 6s 72ms/step - loss: 0.0035 - mse: 0.0055 - val_loss: 2.6882 - val_mse: 44887.4570
Epoch 4/20
78/78 [==============================] - 5s 63ms/step - loss: 0.0026 - mse: 0.0040 - val_loss: 2.6507 - val_mse: 44873.5234
Epoch 5/20
78/78 [==============================] - 6s 72ms/step - loss: 0.0018 - mse: 0.0028 - val_loss: 2.6511 - val_mse: 44873.5273
Epoch 6/20
78/78 [==============================] - 5s 62ms/step - loss: 0.0015 - mse: 0.0024 - val_loss: 2.6509 - val_mse: 44873.5312
Epoch 7/20
78/78 [==============================] - 6s 72ms/step - loss: 0.0014 - mse: 0.0022 - val_loss: 2.6504 - val_mse: 44873.5547
Epoch 8/20
78/78 [==============================] - 6s 72ms/step - loss: 0.0013 - mse: 0.0020 - val_loss: 2.6504 - val_mse: 44873.5312
Epoch 9/20
78/78 [==============================] - 6s 72ms/step - loss: 0.0012 - mse: 0.0019 - val_loss: 2.6502 - val_mse: 44873.5312
Epoch 10/20
78/78 [==============================] - 5s 62ms/step - loss: 0.0011 - mse: 0.0018 - val_loss: 2.6503 - val_mse: 44873.5430
Epoch 11/20
78/78 [==============================] - 5s 62ms/step - loss: 0.0011 - mse: 0.0017 - val_loss: 2.6502 - val_mse: 44873.5312
Epoch 12/20
78/78 [==============================] - 6s 72ms/step - loss: 0.0010 - mse: 0.0016 - val_loss: 2.6501 - val_mse: 44873.5273
Epoch 13/20
78/78 [==============================] - 6s 72ms/step - loss: 9.3551e-04 - mse: 0.0015 - val_loss: 2.6503 - val_mse: 44873.5117
Epoch 14/20
78/78 [==============================] - 5s 63ms/step - loss: 8.4863e-04 - mse: 0.0014 - val_loss: 2.6462 - val_mse: 44873.3672
Epoch 15/20
78/78 [==============================] - 6s 72ms/step - loss: 8.0267e-04 - mse: 0.0013 - val_loss: 2.6452 - val_mse: 44873.3477
Epoch 16/20
78/78 [==============================] - 11s 138ms/step - loss: 7.6101e-04 - mse: 0.0013 - val_loss: 2.6408 - val_mse: 44873.2578
Epoch 17/20
78/78 [==============================] - 6s 76ms/step - loss: 7.3377e-04 - mse: 0.0012 - val_loss: 2.6443 - val_mse: 44873.3320
Epoch 18/20
78/78 [==============================] - 8s 103ms/step - loss: 7.0833e-04 - mse: 0.0012 - val_loss: 2.6474 - val_mse: 44873.4414
Epoch 19/20
78/78 [==============================] - 11s 144ms/step - loss: 6.9184e-04 - mse: 0.0012 - val_loss: 2.6489 - val_mse: 44873.4844
Epoch 20/20
78/78 [==============================] - 9s 120ms/step - loss: 6.6867e-04 - mse: 0.0011 - val_loss: 2.6495 - val_mse: 44873.5117

In [ ]:
def get_predictions(model, x_test_scaled, threshold):
  predictions = model.predict(x_test_scaled)
  # provides losses of individual instances
  errors = tf.keras.losses.msle(predictions, x_test_scaled)
  # 0 = anomaly, 1 = normal
  anomaly_mask = pd.Series(errors) > threshold
  preds = anomaly_mask.map(lambda x: -1 if x == True else 1)
  return preds

def find_threshold(model, x_train_scaled):
  reconstructions = model.predict(x_train_scaled)
  # provides losses of individual instances
  reconstruction_errors = tf.keras.losses.msle(reconstructions, x_train_scaled)

  # threshold for anomaly scores
  threshold = np.mean(reconstruction_errors.numpy()) \
      + np.std(reconstruction_errors.numpy())
  return threshold

threshold = find_threshold(model, x_train_scaled)

In [ ]:
preds = get_predictions(model, x_test_scaled, threshold)
accuracy_score(preds, testY)

0.9998242494839883